# Example configuration using environment variables for secrets or deployment-specific paths
# Use this pattern only when you need environment-driven configuration
domain: "staffer_production_tools"
model: "gemini-2.0-flash"
instruction: "Production Staffer tool aggregation service with environment variables for secrets."

source_servers:
  - name: "excel"
    command: "./excel-mcp-server"
    args: []
    cwd: "${EXCEL_MCP_PATH}"  # Explicit environment variable usage
    tool_filter: [
      "excel_read_sheet",
      "excel_write_to_sheet", 
      "excel_describe_sheets",
      "excel_create_table",
      "excel_copy_sheet"
    ]
    priority: 1
    enabled: "${EXCEL_ENABLED:-true}"  # Explicit environment variable with default
    
  - name: "secure_api_server"
    command: "python3"
    args: ["secure_server.py"]
    cwd: "/path/to/secure-server"  # Direct path for non-secret info
    api_key: "${SECRET_API_KEY}"  # Environment variable for secret
    priority: 2
    enabled: true

tool_selection:
  strategy: "curated"
  exclude_patterns: ["debug_", "internal_", "test_", "_test"]
  max_tools_per_server: "${MAX_TOOLS_PER_SERVER:-25}"  # Explicit env var with default

# Environment variables needed:
# EXCEL_MCP_PATH=/path/to/excel-server
# EXCEL_ENABLED=true
# SECRET_API_KEY=your_secret_key
# MAX_TOOLS_PER_SERVER=25