domain: "staffer_production_tools"
model: "gemini-2.0-flash"
instruction: "Production Staffer tool aggregation service with environment-driven configuration."

source_servers:
  - name: "excel"
    command: "go"
    args: ["run", "cmd/excel-mcp-server/main.go"]
    cwd_env: "EXCEL_MCP_PATH"
    tool_filter: [
      "excel_read_sheet",
      "excel_write_to_sheet", 
      "excel_describe_sheets",
      "excel_create_table",
      "excel_copy_sheet"
    ]
    priority: 1
    enabled: ${EXCEL_ENABLED:-true}
    
  - name: "analytics"
    command: "python"
    args: ["-m", "src.mcp_server.server"]
    cwd_env: "ANALYTICS_MCP_PATH"
    tool_filter: [
      "load_dataset",
      "find_correlations",
      "create_chart",
      "analyze_distributions",
      "detect_outliers",
      "segment_by_column",
      "time_series_analysis",
      "validate_data_quality"
    ]
    priority: 2
    enabled: ${ANALYTICS_ENABLED:-true}

tool_selection:
  strategy: "curated"
  exclude_patterns: ["debug_", "internal_", "test_", "_test"]
  max_tools_per_server: ${MAX_TOOLS_PER_SERVER:-25}

# NO server section - STDIO protocol only